apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  # The application code base (i.e. github or gitlab etc...)
  source:
    repoURL: https://github.com/Wasca/argocd-tutorial.git
    targetRevision: HEAD
    path: dev
  
  # The Destination K8 Cluster
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
